os: linux
dist: trusty
language: r
r:
- release
- devel
cache: packages

before_install:
- sudo apt-get install python
- sudo apt-get install python-pip python-virtualenv
- sudo pip install -U pip
- R -e "install.packages('devtools')"
- R -e "install.packages('tensorflow', repos='http://cran.us.r-project.org')"  

install:
- R -e "devtools::install()"
- R -e "sgmcmc::installTF()"

script:
- travis_wait 30 R CMD build . # Additional wait time, building vignettes takes a while
- travis_wait 30 R CMD check *tar.gz # Additional wait time, building vignettes takes a while
