os: linux
dist: trusty
language: r
r:
- release
- devel
cache: packages

before_install:
- sudo apt-get install python
- sudo apt-get install python-pip python-virtualenv
- sudo pip install -U pip
- R -e "install.packages('devtools')"

install:
- R -e 'devtools::install_deps(dep = T)'
- R -e "devtools::install()"
- R -e "sgmcmc::installTF()"

script:
- travis_wait 30 R CMD build . --no-build-vignettes
- travis_wait 30 R CMD check *tar.gz --no-build-vignettes --no-vignettes
